(() => {
'use strict';
const $=s=>document.querySelector(s),KEY='part6-settings',DB='part6-bgm',STORE='tracks';
let db,url='',preview=false;
const audio=new Audio();audio.loop=true;audio.preload='auto';
const readSettings=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const save=patch=>{const next={...readSettings(),...patch};localStorage.setItem(KEY,JSON.stringify(next));return next};
const toast=m=>{const e=$('#toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(e._b);e._b=setTimeout(()=>e.classList.remove('show'),2200)};
const request=(mode,work)=>new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode),r=work(tx.objectStore(STORE));if(r){r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}else{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)}});
const all=()=>request('readonly',s=>s.getAll());
const one=id=>request('readonly',s=>s.get(id));
const put=v=>request('readwrite',s=>s.put(v));
const clear=()=>request('readwrite',s=>s.clear());
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function displayName(name){return name.replace(/\.[^.]+$/,'').replace(/\s*\(\d+\)\s*$/,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim().replace(/\b\w/g,c=>c.toUpperCase())}
function idFor(name){return displayName(name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`track-${Date.now()}`}
function active(){return !!($('#quizScreen.active')||$('#resultScreen.active'))}
function revoke(){if(url){URL.revokeObjectURL(url);url=''}}
function setButton(){const b=$('#bgmTestBtn');if(b)b.textContent=preview&&!audio.paused?'■ 停止':'▶ 試聴'}
async function load(autoplay=false){const s=readSettings(),track=s.bgmTrack&&await one(s.bgmTrack);audio.pause();revoke();if(!track?.blob){audio.removeAttribute('src');audio.load();return false}url=URL.createObjectURL(track.blob);audio.src=url;audio.volume=Number(s.bgmVolume??.35);audio.load();if(autoplay&&s.bgmEnabled)try{await audio.play()}catch{}return true}
async function play(){const s=readSettings();if(!s.bgmEnabled||!s.bgmTrack)return;audio.volume=Number(s.bgmVolume??.35);if(!audio.src)await load();try{await audio.play()}catch{toast('画面をもう一度タップするとBGMを再生できます')}}
function pause(reset=false){audio.pause();preview=false;setButton();if(reset)audio.currentTime=0}
async function render(){const list=(await all()).sort((a,b)=>a.name.localeCompare(b.name,'en')),sel=$('#bgmTrack'),on=$('#bgmEnabled'),vol=$('#bgmVolume');sel.innerHTML=list.length?list.map(t=>`<option value="${t.id}">${t.name}</option>`).join(''):'<option value="">音源未登録</option>';[sel,on,vol,$('#bgmTestBtn'),$('#bgmClearBtn')].forEach(e=>e.disabled=!list.length);$('#bgmStatus').textContent=`${list.length}曲`;let s=readSettings();if(!list.length){save({bgmEnabled:false,bgmTrack:''});on.checked=false;pause(true);revoke();return list}if(!list.some(t=>t.id===s.bgmTrack)){const first=list.find(t=>t.name.toLowerCase()==='measured progress')||list[0];s=save({bgmTrack:first.id})}sel.value=s.bgmTrack;on.checked=!!s.bgmEnabled;vol.value=String(s.bgmVolume??.35);return list}
async function importFiles(files){const valid=[...files].filter(f=>(f.type.startsWith('audio/')||/\.(mp3|m4a|aac|wav|ogg|opus|webm)$/i.test(f.name))&&f.size<=25*1024*1024);if(!valid.length)return toast('対応する音声ファイルを選択してください');const empty=(await all()).length===0;for(const f of valid){const name=displayName(f.name);await put({id:idFor(f.name),name,blob:f,size:f.size,type:f.type,updatedAt:new Date().toISOString()})}const list=await render();if(empty){const first=list.find(t=>t.name.toLowerCase()==='measured progress')||list[0];save({bgmEnabled:true,bgmTrack:first.id,bgmVolume:'0.35'})}else save({bgmEnabled:true});await render();await load();toast(`${valid.length}曲を端末に保存しました`)}
function bind(){const input=$('#bgmFileInput'),on=$('#bgmEnabled'),sel=$('#bgmTrack'),vol=$('#bgmVolume');$('#bgmImportBtn').onclick=()=>input.click();input.onchange=async()=>{try{await importFiles(input.files)}catch(e){console.error(e);toast('BGMの保存に失敗しました')}input.value=''};on.onchange=()=>{save({bgmEnabled:on.checked});on.checked?(active()||preview)&&play():pause()};sel.onchange=async()=>{const was=!audio.paused;save({bgmTrack:sel.value});await load(was)};vol.oninput=()=>{audio.volume=Number(vol.value);save({bgmVolume:vol.value})};$('#bgmTestBtn').onclick=async()=>{if(preview&&!audio.paused)return pause();preview=true;on.checked=true;save({bgmEnabled:true});await play();setButton()};$('#bgmClearBtn').onclick=async()=>{if(!confirm('端末に保存したBGMをすべて削除しますか？'))return;await clear();await render();toast('BGM音源を削除しました')};document.querySelectorAll('.mode-card[data-mode]').forEach(b=>b.addEventListener('click',play));$('#nextDocumentBtn')?.addEventListener('click',play);$('#homeBtn')?.addEventListener('click',()=>pause(true));$('#backBtn')?.addEventListener('click',()=>pause(true));$('#statsBtn')?.addEventListener('click',()=>pause());$('#settingsBtn')?.addEventListener('click',()=>pause());document.addEventListener('pointerdown',()=>{if(active()&&readSettings().bgmEnabled&&audio.paused&&!preview)play()},{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});audio.onplay=setButton;audio.onpause=setButton;audio.onerror=()=>toast('このBGMを再生できませんでした');addEventListener('beforeunload',revoke)}
(async()=>{try{db=await openDB();bind();const list=await render();if(list.length)await load()}catch(e){console.error(e);toast('BGM保存領域を初期化できませんでした')}})();
})();
